import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: colorScheme.onPrimaryContainer,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.gray30002,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.gray20001,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.blueGray400,
          fontSize: 16.fSize,
          fontFamily: 'Aeonik',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.gray90009,
          fontSize: 14.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.gray700,
          fontSize: 11.fSize,
          fontFamily: 'Gotham Pro',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: appTheme.gray90009,
          fontSize: 40.fSize,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w700,
        ),
        displaySmall: TextStyle(
          color: appTheme.gray90007,
          fontSize: 36.fSize,
          fontFamily: 'Nohemi',
          fontWeight: FontWeight.w500,
        ),
        headlineLarge: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: 32.fSize,
          fontFamily: 'Aeonik',
          fontWeight: FontWeight.w500,
        ),
        headlineSmall: TextStyle(
          color: appTheme.gray90009,
          fontSize: 24.fSize,
          fontFamily: 'Nohemi',
          fontWeight: FontWeight.w600,
        ),
        labelLarge: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: 12.fSize,
          fontFamily: 'Manrope',
          fontWeight: FontWeight.w600,
        ),
        titleLarge: TextStyle(
          color: appTheme.gray90007,
          fontSize: 20.fSize,
          fontFamily: 'Aeonik',
          fontWeight: FontWeight.w500,
        ),
        titleMedium: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: 16.fSize,
          fontFamily: 'Aeonik',
          fontWeight: FontWeight.w500,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: 15.fSize,
          fontFamily: 'Aeonik',
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF5FD148),
    primaryContainer: Color(0XFF343537),
    secondaryContainer: Color(0XFFB9B9B9),

    // Error colors
    errorContainer: Color(0XFF64748B),
    onError: Color(0XFFB1B0B9),
    onErrorContainer: Color(0X0C000E33),

    // On colors(text colors)
    onPrimary: Color(0XFF1D1D25),
    onPrimaryContainer: Color(0XFFFFFFFF),
    onSecondaryContainer: Color(0XFF1E1E1E),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber500 => Color(0XFFFFC107);
  Color get amber600 => Color(0XFFFAB400);
  Color get amber700 => Color(0XFFF59E0B);

  // Black
  Color get black900 => Color(0XFF090A0A);
  Color get black90001 => Color(0XFF040404);
  Color get black90002 => Color(0XFF000000);

  // Blue
  Color get blue500 => Color(0XFF1896F2);
  Color get blueA200 => Color(0XFF5782F1);

  // BlueGray
  Color get blueGray100 => Color(0XFFD0D5DD);
  Color get blueGray10001 => Color(0XFFD0D0D5);
  Color get blueGray10002 => Color(0XFFD9D9D9);
  Color get blueGray10003 => Color(0XFFD3D3D3);
  Color get blueGray10004 => Color(0XFFCDCFD0);
  Color get blueGray10005 => Color(0XFFD8D8D8);
  Color get blueGray10006 => Color(0XFFD1D5DB);
  Color get blueGray10007 => Color(0XFFCBD5E1);
  Color get blueGray10033 => Color(0X33C4CBD7);
  Color get blueGray300 => Color(0XFF94A3B8);
  Color get blueGray30001 => Color(0XFF8696BB);
  Color get blueGray400 => Color(0XFF82808F);
  Color get blueGray800 => Color(0XFF344053);
  Color get blueGray900 => Color(0XFF2B2A30);

  // DeepOrange
  Color get deepOrange300 => Color(0XFFFF7D60);
  Color get deepOrange50 => Color(0XFFFEE2E2);

  // DeepPurple
  Color get deepPurple300 => Color(0XFF9473D9);
  Color get deepPurple50 => Color(0XFFEBE9FE);
  Color get deepPurple900 => Color(0XFF3E1C96);
  Color get deepPurpleA200 => Color(0XFF9747FF);
  Color get deepPurpleA20001 => Color(0XFF7959F8);
  Color get deepPurpleA400 => Color(0XFF4425F5);
  Color get deepPurpleA40001 => Color(0XFF6838EE);
  Color get deepPurpleA700 => Color(0XFF2A00FF);

  // Gray
  Color get gray100 => Color(0XFFF6F6F6);
  Color get gray10001 => Color(0XFFF1F5F9);
  Color get gray10002 => Color(0XFFF3F3F4);
  Color get gray10003 => Color(0XFFF0FDF4);
  Color get gray10004 => Color(0XFFF4F4F4);
  Color get gray10005 => Color(0XFFF4F3FF);
  Color get gray10006 => Color(0XFFF5F5F5);
  Color get gray200 => Color(0XFFE5E7EB);
  Color get gray20001 => Color(0XFFECECEC);
  Color get gray20002 => Color(0XFFE8E7EA);
  Color get gray300 => Color(0XFFDADADA);
  Color get gray30001 => Color(0XFFDBDBDB);
  Color get gray30002 => Color(0XFFDCDBE0);
  Color get gray400 => Color(0XFFB0B0B0);
  Color get gray50 => Color(0XFFFBFBFC);
  Color get gray500 => Color(0XFFA4A4A4);
  Color get gray50001 => Color(0XFFADADAD);
  Color get gray50019 => Color(0X19999999);
  Color get gray5001 => Color(0XFFF7F5FE);
  Color get gray5002 => Color(0XFFF9F9F9);
  Color get gray5003 => Color(0XFFF8F9FD);
  Color get gray600 => Color(0XFF7A7A7A);
  Color get gray60001 => Color(0XFF717171);
  Color get gray60002 => Color(0XFF6B7280);
  Color get gray700 => Color(0XFF565560);
  Color get gray900 => Color(0XFF141414);
  Color get gray90001 => Color(0XFF24222B);
  Color get gray90002 => Color(0XFF0F172A);
  Color get gray90003 => Color(0XFF2B2B22);
  Color get gray90004 => Color(0XFF121212);
  Color get gray90005 => Color(0XFF0D1B34);
  Color get gray90006 => Color(0XFF181926);
  Color get gray90007 => Color(0XFF2A2A2A);
  Color get gray90008 => Color(0XFF181620);
  Color get gray90009 => Color(0XFF161518);
  Color get gray90014 => Color(0X140E172A);

  // Green
  Color get green50 => Color(0XFFDCFCE7);
  Color get green500 => Color(0XFF47BD68);
  Color get green5001 => Color(0XFFE0FFEC);
  Color get green900 => Color(0XFF20603D);
  Color get greenA100 => Color(0XFFBBF7D0);
  Color get greenA700 => Color(0XFF22C55E);
  Color get greenA70001 => Color(0XFF1CCD5B);
  Color get greenA70002 => Color(0XFF00BC4B);

  // Indigo
  Color get indigo100 => Color(0XFFBCB4FD);
  Color get indigo300 => Color(0XFF6798E1);
  Color get indigo50 => Color(0XFFE6E9ED);
  Color get indigo5001 => Color(0XFFD9D6FE);
  Color get indigo5002 => Color(0XFFE2E8F0);
  Color get indigo600 => Color(0XFF3D5A98);
  Color get indigo700 => Color(0XFF374993);
  Color get indigo70001 => Color(0XFF364992);
  Color get indigo90026 => Color(0X26001753);
  Color get indigoA200 => Color(0XFF5D5FEF);

  // LightBlue
  Color get lightBlue10007 => Color(0X07B2DDFF);

  // LightBlueAf
  Color get lightBlueA4000f => Color(0X0F00BDFF);

  // LightGreen
  Color get lightGreen300 => Color(0XFF9CE390);
  Color get lightGreen30001 => Color(0XFF9BE38F);
  Color get lightGreen500 => Color(0XFF83BF4F);
  Color get lightGreen50001 => Color(0XFF6EE755);

  // Orange
  Color get orange10007 => Color(0X07FFDCBF);

  // Pink
  Color get pink400 => Color(0XFFE82C81);
  Color get pink40001 => Color(0XFFEF4565);

  // Pinkf
  Color get pink5000f => Color(0X0FFE265B);

  // Purple
  Color get purple800 => Color(0XFF6A00A3);

  // Redc
  Color get red2004c => Color(0X4CE8899E);

  // Red
  Color get red50 => Color(0XFFFEF2F2);
  Color get red500 => Color(0XFFEF4444);
  Color get red700 => Color(0XFFBD3D44);
  Color get redA200 => Color(0XFFFF5A5F);
  Color get redA400 => Color(0XFFFF003A);
  Color get redA700 => Color(0XFFFF0000);

  // Teal
  Color get teal400 => Color(0XFF26A17B);
  Color get teal700 => Color(0XFF008753);

  // White
  Color get whiteA700 => Color(0XFFFCFCFE);

  // Yellow
  Color get yellow100 => Color(0XFFFEF3C7);
  Color get yellow50 => Color(0XFFFFFBEB);
  Color get yellow900 => Color(0XFFF7931A);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
