import 'package:flutter/material.dart';
import 'package:medicon/core/app_export.dart';
import 'package:medicon/widgets/app_bar/appbar_leading_image.dart';
import 'package:medicon/widgets/app_bar/custom_app_bar.dart';
import 'package:medicon/widgets/custom_elevated_button.dart';
import 'package:medicon/widgets/custom_icon_button.dart';

class SuccessStateNewPasswordScreen extends StatelessWidget {const SuccessStateNewPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: 375.h, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 15.v), Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 5.adaptSize, width: 5.adaptSize, margin: EdgeInsets.only(top: 146.v), decoration: BoxDecoration(color: appTheme.greenA100, borderRadius: BorderRadius.circular(2.h))), Container(height: 150.v, width: 154.h, margin: EdgeInsets.only(left: 1.h), child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.only(left: 3.h), padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 8.v), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.circleBorder75), child: Container(padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 11.v), decoration: AppDecoration.outlineGray90002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgTrophy, height: 35.v, width: 23.h), SizedBox(height: 15.v), CustomImageView(imagePath: ImageConstant.imgTelevisionGray10001, height: 25.v, width: 82.h), SizedBox(height: 7.v), CustomImageView(imagePath: ImageConstant.imgTelevisionGray10001, height: 25.v, width: 82.h)])))), Align(alignment: Alignment.topLeft, child: Container(height: 5.adaptSize, width: 5.adaptSize, margin: EdgeInsets.only(top: 20.v), decoration: BoxDecoration(color: appTheme.greenA100, borderRadius: BorderRadius.circular(2.h)))), CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(8.h), decoration: IconButtonStyleHelper.outlineOnPrimaryContainer, alignment: Alignment.bottomRight, child: CustomImageView(imagePath: ImageConstant.imgCheck))])), Container(height: 5.adaptSize, width: 5.adaptSize, margin: EdgeInsets.only(left: 12.h, top: 40.v, bottom: 106.v), decoration: BoxDecoration(color: appTheme.greenA100, borderRadius: BorderRadius.circular(2.h)))]), SizedBox(height: 44.v), Text("Password Updated!", style: CustomTextStyles.headlineSmallGray90002Bold), SizedBox(height: 16.v), SizedBox(width: 235.h, child: Text("Your password has been set up successfully.", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLarge_1.copyWith(height: 1.60)))])), bottomNavigationBar: _buildProceedToSignIn(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 374.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgVectorBlack90002, margin: EdgeInsets.fromLTRB(21.h, 21.v, 340.h, 21.v))); } 
/// Section Widget
Widget _buildProceedToSignIn(BuildContext context) { return CustomElevatedButton(text: "Proceed to Sign in", margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 66.v), onPressed: () {onTapProceedToSignIn(context);}); } 
/// Navigates to the loginOneScreen when the action is triggered.
onTapProceedToSignIn(BuildContext context) { Navigator.pushNamed(context, AppRoutes.loginOneScreen); } 
 }
